### ISSUE TITLE
Delete All

### ISSUE THREAD

**Issue by shrimpie1911** [kongzii/xiaomi-yi-py#1]
Hi, I'm currently trying to delete all file using the scripts. I've found that the msg_id for delete is 1281 and i can delete file manually by using their name. But i want to automise it, for example i want to delete everything by the end of each day. Can someone help please.

Thank you in advance for the help and sorry for my bad english.

**Comment by kongzii** [comment]
Hi, sorry, but such functionality is just not supported in the script. It is not an issue. 

Unfortunately, I do not have Yi camera anymore, so I can not investigate and implement it.
You are welcome to implement it and give a pull request.
